### PR TITLE
Working on Flask API and Barcode API

### PR DESCRIPTION
**Pull request by AvikantSrivastava**

### CODE REVIEW

**Comment by AvikantSrivastava** [comment]
@shresth26 dont merge it now, wait for me to complete the code.

**Comment by AvikantSrivastava** [comment]
## Post requests are now working 🍺🍺🍺🍺
### I have added dummy code (commented) to test the connection
image
image

**Comment by shresth26** [comment]
> @shresth26 dont merge it now, wait for me to complete the code.

Okay mate

**Comment by AvikantSrivastava** [comment]
# Checkpoint 2
## Flask API `app.py`
- Decoding of images from byte 64 string
- Barcode module integration
- Barcode from image string

## Client app `client.py`
- Encoding of images into byte64 strings
- Sending image data over POST requests


# Test run
### Sample barcode image `barcode_test.jpg`
barcode_test

### Client side POST request call 
image

### Server side POST request Processing
image

**Comment by shresth26** [comment]
@AvikantSrivastava  Everything looks fantastic thus far

**Comment by AvikantSrivastava** [comment]
@shresth26
The barcode is now completely functional.
You may now merge the PR

**Comment by shresth26** [comment]
> @shresth26
> The barcode is now completely functional.
> You may now merge the PR

Sure I will

**Pull request merged**
